version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:1.29.0-alpine
    volumes:
      - './Data/Vaultwarden:/data'
    restart: always
    environment:
      DOMAIN: '${DOMAIN}'
      SIGNUPS_ALLOWED: '${SIGNUPS_ALLOWED}'
#      SIGNUPS_DOMAINS_WHITELIST: '${SIGNUPS_DOMAINS_WHITELIST}'
      SIGNUPS_VERIFY: '${SIGNUPS_VERIFY}'
      INVITATIONS_ALLOWED: '${INVITATIONS_ALLOWED}'
      SHOW_PASSWORD_HINT: '${SHOW_PASSWORD_HINT}'
#      ADMIN_TOKEN: '${ADMIN_TOKEN}'
#      DISABLE_ADMIN_TOKEN: '${DISABLE_ADMIN_TOKEN}'

      # ORGANIZATIONS
      ORG_EVENTS_ENABLED: '${ORG_EVENTS_ENABLED}'
      ORG_GROUPS_ENABLED: '${ORG_GROUPS_ENABLED}'
#      EVENT_CLEANUP_SCHEDULE: '${EVENT_CLEANUP_SCHEDULE}'

      # Mail Server
#      SMTP_HOST: '${SMTP_HOST}'
#      SMTP_FROM: '${SMTP_FROM}'
#      SMTP_PORT: '${SMTP_PORT}'
#      SMTP_SECURITY: '${SMTP_SECURITY}'
#      SMTP_USERNAME: '${SMTP_USERNAME}'
#      SMTP_PASSWORD: '${SMTP_PASSWORD}'

      # Logging
      LOG_FILE: '/data/vaultwarden.log'
      LOG_LEVEL: '${LOG_LEVEL}'
#      USE_SYSLOG: '${USE_SYSLOG}'
#      EXTENDED_LOGGING: '${EXTENDED_LOGGING}'

      # YubiKey authentication
#      YUBICO_CLIENT_ID: '${YUBICO_CLIENT_ID}'
#      YUBICO_SECRET_KEY: '${YUBICO_SECRET_KEY}'
#      YUBICO_SERVER: '${YUBICO_SERVER}'

      # Push Notifications
      PUSH_ENABLED: '${PUSH_ENABLED}'
      PUSH_INSTALLATION_ID: '${PUSH_INSTALLATION_ID}'
      PUSH_INSTALLATION_KEY: '${PUSH_INSTALLATION_KEY}'

  nginx:
    build: './Docker/nginx'
    links:
      - vaultwarden
      - vw_backup
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
    command: /bin/sh -c "/run_nginx.sh"
    restart: on-failure
    networks:
      - default
      - traefik-proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.tls=true'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.entrypoints=https'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.rule=Host(`${VIRTUAL_HOST}`)'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.service=${PROJECT_IDENTIFIER}'
      - 'traefik.http.services.${PROJECT_IDENTIFIER}.loadbalancer.server.port=80'

  vw_backup:
    image: bruceforce/bw_backup:latest #swap tag to rpi3 to run on a raspberry pi
    restart: on-failure
    depends_on:
      - vaultwarden
    volumes:
      - './Data/Vaultwarden:/data'
      - './Data/Vaultwarden-Backup:/backup'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - DB_FILE=/data/db.sqlite3
      - BACKUP_FILE=/backup/backup.sqlite3
      - BACKUP_FILE_PERMISSIONS=700
      - CRON_TIME=0 1 * * *
      - TIMESTAMP=false
      - UID=0
      - GID=0

networks:
  default:
    driver: bridge
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
    external: true
